# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10C1KahW2IgcvarHuR5WOLBDtRVHFSYm2
"""

from google.colab.patches import cv2_imshow
import cv2

def taom(belgi):
  if belgi =="Sho'rva":
    rasm=cv2.imread('1.jpg')
    cv2_imshow(rasm)
    return "18 000"
  elif belgi == "Palov":
    rasm=cv2.imread('2.jpg')
    cv2_imshow(rasm)
    return "30 000"
  elif belgi == "Somsa":
    rasm=cv2.imread('3.jpg')
    cv2_imshow(rasm)
    return "10 000"
  elif belgi == "Manti":
    rasm=cv2.imread('4.jpg')
    cv2_imshow(rasm)
    return "8 000"
  elif belgi == "Kaboblar":
    rasm=cv2.imread('5.jpg')
    cv2_imshow(rasm)
    return "25 000"
  elif belgi == "Bifshteks":
    rasm=cv2.imread('6.jpg')
    cv2_imshow(rasm)
    return "30 000"
  elif belgi == "Mastava":
    rasm=cv2.imread('7.jpg')
    cv2_imshow(rasm)
    return "20 000"
  elif belgi == "Lag'mon":
    rasm=cv2.imread('8.jpg')
    cv2_imshow(rasm)
    return "30 000"
  elif belgi == "Gamburger":
    rasm=cv2.imread('9.jpg')
    cv2_imshow(rasm)
    return "35 000"
  else:
    return "Ma'lumot topilmadi"
belgi = input("Taom nomini kiriting ")
natija=taom(belgi)
print(natija)